config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
   get "/" => "homes#top"
   resources :items, only: [:index, :new, :create, :show, :edit, :update]
   resources :customers, only: [:index, :show, :edit, :update]
   resources :orders, only: [:show]
  end

  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  scope module: :public do
   root to: 'homes#top'
   get "about" => "homes#about", as:'about'
   get "customers/information" => "customers#show"
   get "customers/information/edit" => "customers#edit"
   patch "customers/information" => "customers#update"
   get "customers/confirm_withdraw" => "customers#confirm_withdraw"
   patch "customers/withdraw" => "customers#withdraw"
   delete "cart_items/destroy_all" => "cart_items#destroy_all"
   post "orders/confirm" => "orders#confirm"
   get "orders/complete" => "orders#complete"
   resources :items, only: [:index, :show]
   resources :cart_items, only: [:index, :update, :create, :destroy]
   resources :orders, only: [:new, :create, :index, :show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, through: :order_details

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true, numericality: {only_integer: true}

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [250, 250]).processed
  end

  def with_tax_price
    (price*1.1).floor
  end

  #def add_tax_price
    #(self.price * 1.10).round
  #end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<body>
 <main>
   <div class="container">
   <br>
   <h2>商品編集</h2>
   <%= form_with model: @item, url:admin_item_path, local:true do |f| %>

   <br>
   <div class="col-xl-12">
     <table class="item-edit mx-auto">
      <tr>
        <th class="col-sm-3"><%= f.label :商品画像 %></th>
        <td><%= f.file_field:image, accept:"image/*" %></td>
      </tr>

      <tr>
        <th class="col-sm-3"><%= f.label :商品名 %></th>
        <td><%= f.text_field :name, size:"30*5" %></td>
      </tr>

      <tr>
        <th class="col-sm-3"><%= f.label :商品説明 %></th>
        <td><%= f.text_area :introduction, size:"30x5" %></td>
      </tr>

      <tr>
        <th class="col-sm-3"><%= f.label :税抜価格 %>
        <td>
          <%= f.text_field :price, size:"30*5"%>
          <%= f.label :円 %>
        </td>
      </tr>
     </table>
    </div>

     <br>
     <div class="btn-class text-center ml-5">
      <%= f.submit "変更を保存", class: "btn btn-success pull-right w-25" %>
     </div>

   <% end %>

   </div>
   <br>
   <br>
 </main>
</body>

app/views/admin/items/index.html.erb
<body>
    <main>
      <div class="container">
        <div class="row">

            <div class="col-xl-10">
              <h3 class="col-sm-2">商品一覧</h3>
            </div>

              <div class="text-right col-xl-2 pt-2">
                <%= link_to new_admin_item_path do %>
                 <button type="button" class="btn-outline-dark btn-circle btn-lg mt-4">＋</button>
                <% end %>
              </div>

              <br>
              <table class="table item-table col-xl-12">
                <thead class="table-active">
                  <tr>
                    <th>商品ID</th>
                    <th>商品名</th>
                    <th>税抜価格</th>
                  </tr>
                </thead>

                <tbody>
                  <% @items.each do |item| %>
                   <tr>
                     <th><%= item.id %></th>
                     <th><%= link_to item.name,admin_item_path(item.id) %></th>
                     <th><%= (item.price).to_s(:delimited) %></th>
                   </tr>
                  <% end %>
                </tbody>
              </table>
         </div>
      </div>

          <br>
          <div class="container">
            <div class="row">
              <div class="col-md-5"></div>
              <div class="paginate-item ml-5">
                <%= paginate @items, class: "center-block" %>
              </div>
            </div>
          </div>
          <br>
    </main>
</body>

app/views/admin/items/new.html.erb
<body>
  <main>
    <div class="container">
     <br>
     <h2>商品新規登録</h2>
     <br>
     <br>
     <div class="col-lg-12">

      <%= form_with model: @item, url:admin_items_path, local:true do |f| %>

        <div class="field-group new_item">
         <%= f.label :商品画像, class: "col-lg-2" %>
         <%= f.file_field:image, accept:"image/*" %>
        </div>
        <br>

        <div class="field-group new_item">
         <%= f.label :商品名, class: "col-lg-2" %>
         <%= f.text_field :name, size:"30*5" %>
        </div>
        <br>

        <div class="field-group new_item">
         <%= f.label :商品説明, class: "col-lg-2" %>
         <%= f.text_area :introduction, size:"29*70" %>
        </div>
        <br>

        <div class="field-group new_item">
         <%= f.label :税抜価格, class: "col-lg-2" %>
         <%= f.text_field :price, size:"30*5"%>
         <%= f.label :円 %>
        </div>

        <br>
        <div class="text-center mt-5 ml-2">
         <%= f.submit "新規登録", class: "btn btn-success w-25" %>
        </div>

      <% end %>

     </div>
    </div>
    <br>
    <br>
    <br>
    <br>
  </main>
</body>

app/views/admin/items/show.html.erb
<body>
  <main>
      <br>
      <br>
      <h2 class="item-show-admin">商品詳細</h2>
      <br>

        <div class="container mx-auto">
          <div class="row">
            <div class="col-lg-5 admin-item ml-5">
              <div class="item-image">
                <%= image_tag @item.get_image, size: "400x300" %>
              </div>
            </div>
            <div class="col-lg-5 mt-5">
              <table class="admin-item-table", width="100%">
                <tr>
                  <th width="20%">商品名</th>
                  <td><%= @item.name %></td>
                </tr>

                <tr>
                  <th width="20%">商品説明</th>
                  <td><%= @item.introduction %></td>
                </tr>

                <tr>
                  <th width="30%">税込価格<br>（税抜価格）</th>
                  <td><%= (@item.price*1.1).floor.to_s(:delimited) %>(<%= (@item.price).floor.to_s(:delimited) %>)円</td>
                </tr>
              </table>

            </div>
          </div>
        </div>
            <br>
            <div class="text-center mt-5">
              <%= link_to "編集する", edit_admin_item_path(@item.id), class:"btn btn-success w-25" %>
            </div>
    <br>
    <br>
  </main>
</body>