config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
   get "/" => "homes#top"
   resources :items, only: [:index, :new, :create, :show, :edit, :update]
   resources :customers, only: [:index, :show, :edit, :update]
   resources :orders, only: [:show]
  end

  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  scope module: :public do
   root to: 'homes#top'
   get "about" => "homes#about", as:'about'
   get "customers/information" => "customers#show"
   get "customers/information/edit" => "customers#edit"
   patch "customers/information" => "customers#update"
   get "customers/confirm_withdraw" => "customers#confirm_withdraw"
   patch "customers/withdraw" => "customers#withdraw"
   delete "cart_items/destroy_all" => "cart_items#destroy_all"
   post "orders/confirm" => "orders#confirm"
   get "orders/complete" => "orders#complete"
   resources :items, only: [:index, :show]
   resources :cart_items, only: [:index, :update, :create, :destroy]
   resources :orders, only: [:new, :create, :index, :show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items, dependent: :destroy
  has_many :orders
  
  validates :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, presence: true
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path
    else
      render 'edit'
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_deleted)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<body>
  <main>
      <div class="container">
        <br>
        <h2><%= (@customer.last_name + @customer.first_name) %>さんの会員情報編集</h2>

        <%= form_with(model: @customer, url:admin_customer_path, local: true, method: :patch) do |f| %>

        <br>
        <br>
        <div class="col-xl-12">
            <table class="customer-edit col-xl-8">
              <tr>
                <th><%= f.label :"会員ID" %></th>
                <td><%= f.label :"#{@customer.id}" %></td>
              </tr>

              <tr>
                <th><%= f.label :"氏名" %></th>
                <td>
                  <%= f.text_field :last_name %>&emsp;&emsp;
                  <%= f.text_field :first_name %>
                </td>
              </tr>

              <tr>
                <th><%= f.label :"フリガナ" %></th>
                <td>
                  <%= f.text_field :last_name_kana %>&emsp;&emsp;
                  <%= f.text_field :first_name_kana %>
                </td>
              </tr>

              <tr>
                <th><%= f.label :"郵便番号" %></th>
                <td><%= f.text_field :postal_code %></td>
              </tr>

              <tr>
                <th><%= f.label :"住所" %></th>
                <td><%= f.text_field :address, size:"46*5" %></td>
              </tr>

              <tr>
                <th><%= f.label :"電話番号" %></th>
                <td><%= f.text_field :telephone_number %></td>
              </tr>

              <tr>
                <th><%= f.label :"メールアドレス" %></th>
                <td><%= f.text_field :email %></td>
              </tr>

              <tr>
                <th><%= f.label :"会員ステータス" %>
                <td>
                  <%= f.radio_button :is_deleted, false %>
                  <%= f.label :is_deleted, "有効", {value: :false, style: "display: inline-block;"} %>
                  <%= f.radio_button :is_deleted, true %>
                  <%= f.label :is_deleted, "退会", {value: :true, style: "display: inline-block;"} %>
                </td>
              </tr>
            </table>
            <br>
            <br>
            <div class="btn-class text-center">
              <%= f.submit '変更を保存', class: "btn btn-success w-25" %>
            </div>

            <% end %>
        </div>
      </div>
      <br>
      <br>
  </main>
</body>

app/views/admin/customers/index.html.erb
<body>
  <main>
    <div class="container">
     <br>
     <h2>会員一覧</h2>
     <br>

     <table class="table customer-table">
       <thead class="table-active">
         <tr>
           <th>会員ID</th>
           <th>氏名</th>
           <th>メールアドレス</th>
           <th>ステータス</th>
         </tr>
       </thead>

       <tbody>
         <% @customers.each do |customer| %>
          <tr>
            <th>
              <%= customer.id %>
            </th>
            <td>
              <%= link_to (customer.last_name + customer.first_name), admin_customer_path(customer.id) %>
            </th>
            <th>
              <%= customer.email %>
            </th>
            <th>
              <% if customer.is_deleted %>
               退会
              <% else %>
               有効
              <% end %>
            </th>
          </tr>
         <% end %>
         <%= paginate @customers %>
       </tbody>
     </table>
    </div>
  </main>
</body>

app/views/admin/customers/show.html.erb
<body>
  <main>
      <div class="container">
        <div class="row">
          <div class="col-xl-12">
            <br>
            <h2><%= (@customer.last_name + @customer.first_name) %>さんの会員詳細</h2>

            <br>
            <table class="customer-show col-xl-5 ml-5">
              <tr>
                <th><strong>会員ID</strong></th>
                <td><%= @customer.id %></td>
              </tr>

              <tr>
                <th><strong>氏名</strong></th>
                <td><%= (@customer.last_name + @customer.first_name) %></td>
              <tr>

              <tr>
                <th><strong>フリガナ</strong></th>
                <td><%= (@customer.last_name_kana + @customer.first_name_kana) %></td>
              </re>

              <tr>
                <th><strong>郵便番号</strong></th>
                <td><%= @customer.postal_code.to_s.insert(3,"-") %></td>
              </tr>

              <tr>
                <th><strong>住所</strong></th>
                <td><%= @customer.address %></td>
              </tr>

              <tr>
                <th><strong>電話番号</strong></th>
                <td><%= @customer.telephone_number %></td>
              </tr>

              <tr>
                <th><strong>メールアドレス</strong></th>
                <td><%= @customer.email %></td>
              </tr>

              <div>
                 <th><strong class="col-xs-2">会員ステータス</strong></th>
                 <td>
                  <% if @customer.is_deleted %>
                   <span class="bg-dranger">退会</span>
                  <% else %>
                   <span class="bg-primary">有効</span>
                  <% end %>
                 </td>
              </div>
            </table>
            <br>
            <br>
            <div class="text-center">
              <%= link_to "編集する", edit_admin_customer_path, class: "btn btn-success w-25" %>&emsp;&emsp;
              <%= link_to "注文履歴一覧を見る", admin_path, class: "btn btn-primary w-25" %>
            </div>

          </div>
        </div>
    </div>
    <br>
    <br>
  </main>
</body>