config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
   get "/" => "homes#top"
   resources :items, only: [:index, :new, :create, :show, :edit, :update]
   resources :customers, only: [:index, :show, :edit, :update]
   resources :orders, only: [:show]
  end

  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  scope module: :public do
   root to: 'homes#top'
   get "about" => "homes#about", as:'about'
   get "customers/information" => "customers#show"
   get "customers/information/edit" => "customers#edit"
   patch "customers/information" => "customers#update"
   get "customers/confirm_withdraw" => "customers#confirm_withdraw"
   patch "customers/withdraw" => "customers#withdraw"
   delete "cart_items/destroy_all" => "cart_items#destroy_all"
   post "orders/confirm" => "orders#confirm"
   get "orders/complete" => "orders#complete"
   resources :items, only: [:index, :show]
   resources :cart_items, only: [:index, :update, :create, :destroy]
   resources :orders, only: [:new, :create, :index, :show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details

  enum payment_method:{credit_card:0,transfer:1}

  validates :postal_code, presence: true
  validates :address, presence: true
  validates :name, presence: true


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<body>
 <main>
   <div class="container">
     <br>
     <h3>注文履歴詳細</h3>
      <div class="col-lg-12">
          <div class="row">
            <table class="table public-order col-lg-5">
              <tr>
                <th><strong class="col-xs-5">購入者</strong></th>
                <td>
                  <%= link_to admin_customer_path(@order.customer.id) do %>
                   <%= @order.customer.last_name %><%= @order.customer.first_name %>
                  <% end %>
                </td>
              </tr>

              <tr>
                <th><strong class="col-xs-5">注文日</strong></th>
                <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
              </tr>

              <tr>
                <th><strong class="col-xs-5">配送先</strong></th>
                <td>
                  〒<%= (@order.customer.postal_code).to_s.insert(3, "-") %>
                  <%= @order.customer.address %><br>
                  <%= @order.customer.last_name %><%= @order.customer.first_name %>
                </td>
              </tr>

              <tr>
                <th><strong class="col-xs-5">支払方法</strong></th>
                <td> <%= @order.payment_method_i18n %></td>
              </tr>
            </table>
          </div>
          <br>

           <div class="row">
             <table class="order-show-table col-xl-8">
               <thead class="table-active">
                <tr>
                  <th>商品名</th>
                  <th>単価（税込）</th>
                  <th>数量</th>
                  <th>小計</th>
                </tr>
               </thead>

              <tbody>
               <% @order_details.each do |order_detail| %>
                <tr>
                  <td><%= order_detail.item.name %></td>
                  <td><%= (order_detail.price*1.1).floor.to_s(:delimited) %></td>
                  <td><%= order_detail.amount %></td>
                  <td><%= (order_detail.price*order_detail.amount*1.1).floor.to_s(:delimited) %></td>
                </tr>
              </tbody>
              <% end %>
             </table>

             <table class="total-price col-xl-3">
               <tr>
                 <th><strong>商品合計</strong></th>
                 <td><%= (@order.total_price-@order.postage).to_s(:delimited) %>円</td>
               </tr>

              <tr>
                 <th><strong>送料</strong></th>
                 <td><%= @order.postage %>円</td>
              </tr>

              <tr>
                 <th><strong>請求金額合計</strong></th>
                 <td><%= @order.total_price.to_s(:delimited) %>円</td>
              </tr>
            </table>
          </div>
          <br>
      </div>
    </div>
    <br>
 </main>
</body>