config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
   get "/" => "homes#top"
   resources :items, only: [:index, :new, :create, :show, :edit, :update]
   resources :customers, only: [:index, :show, :edit, :update]
   resources :orders, only: [:show]
  end

  devise_for :customers, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  scope module: :public do
   root to: 'homes#top'
   get "about" => "homes#about", as:'about'
   get "customers/information" => "customers#show"
   get "customers/information/edit" => "customers#edit"
   patch "customers/information" => "customers#update"
   get "customers/confirm_withdraw" => "customers#confirm_withdraw"
   patch "customers/withdraw" => "customers#withdraw"
   delete "cart_items/destroy_all" => "cart_items#destroy_all"
   post "orders/confirm" => "orders#confirm"
   get "orders/complete" => "orders#complete"
   resources :items, only: [:index, :show]
   resources :cart_items, only: [:index, :update, :create, :destroy]
   resources :orders, only: [:new, :create, :index, :show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header class="shadow-sm">
     <nav class="navbar navbar-expand-lg navbar-dark bg-info">
      <div class="container">
       <a class="navbar-brand" href="/">NaganoCake</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
       </button>

        <% if customer_signed_in? %>
         <div class="customer_name">
          <p>ようこそ、<%= current_customer.last_name %>さん！</p>
         </div>
        <% end %>

       <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">

        <% if admin_signed_in? %>
         <li class="nav-item">
          <%= link_to "商品一覧", admin_items_path, class: 'nav-link text-light' %>
         </li>
         <li class="nav-item">
          <%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-light' %>
         </li>
         <li class="nav-item">
          <%= link_to "注文履歴一覧", admin_path, class: 'nav-link text-light' %>
         </li>
         <li class="nav-item">
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-light' %>
         </li>
        <% elsif customer_signed_in? %>
         <!--<li class="customer_name mx-auto">-->
         <!-- ようこそ、<%#= current_customer.last_name %>さん！-->
         <!--</li>-->
         <li class="nav-item">
          <%= link_to "マイページ", customers_information_path, class: 'nav-link text-light' %>
         </li>
         <li class="nav-item">
          <%= link_to "商品一覧", items_path, class: 'nav-link text-light' %>
         </li>
         <li class="nav-item">
          <%= link_to "カート", cart_items_path, class: 'nav-link text-light' %>
         </li>
         <li class="nav-item">
          <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-light' %>
         </li>
        <% else %>
         <li class="nav-item">
          <%= link_to "About", about_path, class: 'nav-link text-light' %>
         </li>
         <li class="nav-item">
          <%= link_to "商品一覧", items_path, class: 'nav-link text-light' %>
         </li>
         <li class="nav-item">
          <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-light' %>
         </li>
         <li class="nav-item">
          <%= link_to "ログイン", customer_session_path, class: 'nav-link text-light' %>
         </li>
        <% end %>

        </ul>
       </div>
      </div>
     </nav>
   </header>
    <main>
     <%#= notice %>
     <%= yield %>
     <%= render 'public/footer' %>
    </main>
  </body>
</html>